log_filepath = "C:/Users/Public/Daybreak Game Company/Installed Games/EverQuest/Logs/eqlog_Zlem_fangbreaker.txt"
roster_filepath = "C:/Users/Public/Daybreak Game Company/Installed Games/EverQuest/"
roster_filename_default = "gr.txt"
log_file_path = "jmq.log"
player_stats_file_path = "player_stats.json"

spell_slot_keys = {1: '2', 2: '3', 3: '4', 4: '5', 5: '7', 6: '8', 7: '9', 8: '0'}

spells = {
    'heal': {'slot': 1, 'casttime': 3.8, 'recasttime': 1.5},
    'sow': {'slot': 8, 'casttime': 4.5, 'recasttime': 3.5},
    'gsow': {'slot': 8, 'casttime': 6.5, 'recasttime': 9.0},
    'potg': {'slot': 8, 'casttime': 4.0, 'recasttime': 18.0},
    'pot9': {'slot': 3, 'casttime': 6.0, 'recasttime': 1.5},
    'lev': {'slot': 8, 'casttime': 3.0, 'recasttime': 1.5},
    'cl': {'slot': 4, 'casttime': 10.0, 'recasttime': 6.0},
    'chloro': {'slot': 8, 'casttime': 4.0, 'recasttime': 1.5},
    'gchloro': {'slot': 8, 'casttime': 9.0, 'recasttime': 12},
    'thorns': {'slot': 8, 'casttime': 3.0, 'recasttime': 1.5},
    'gthorns': {'slot': 8, 'casttime': 3.0, 'recasttime': 1.5},
    'blades': {'slot': 8, 'casttime': 3.0, 'recasttime': 1.5},
    'bracken': {'slot': 8, 'casttime': 2.5, 'recasttime': 1.5},
    'regrowth': {'slot': 8, 'casttime': 4.0, 'recasttime': 1.5},
    'replenishment': {'slot': 6, 'casttime': 6.5, 'recasttime': 1.5},
    'gregrowth': {'slot': 8, 'casttime': 6.0, 'recasttime': 1.5},
    'sln': {'slot': 8, 'casttime': 4.0, 'recasttime': 12.0},
    'natureskin': {'slot': 8, 'casttime': 4.0, 'recasttime': 1.5},
    'stormstrength': {'slot': 8, 'casttime': 3.25, 'recasttime': 1.5},
    'girdleofkarana': {'slot': 8, 'casttime': 5.0, 'recasttime': 7.5},
    'nmight': {'slot': 8, 'casttime': 2.5, 'recasttime': 1.5},
    'cs': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'gd': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'ic': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'wl': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'dl': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'bb': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'feerrott': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'nk': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'lava': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'misty': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'ro': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'steamfont': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'sfg': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'toxx': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'sf': {'slot': 8, 'casttime': 9.0, 'recasttime': 1.5},
    'ej': {'slot': 8, 'casttime': 9.0, 'recasttime': 1.5},
    'ba': {'slot': 8, 'casttime': 6.0, 'recasttime': 1.5},
    'invis': {'slot': 8, 'casttime': 3.25, 'recasttime': 1.5},
    'counteractdisease': {'slot': 8, 'casttime': 3.0, 'recasttime': 1.5},
    'resistdisease': {'slot': 8, 'casttime': 3.5, 'recasttime': 1.5},
    'dawn': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'grim': {'slot': 5, 'casttime': 10.0, 'recasttime': 6.0},
    'nexus': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'twi': {'slot': 7, 'casttime': 10.0, 'recasttime': 6.0},
    'soe': {'slot': 2, 'casttime': 3.0, 'recasttime': 1.5},
    'potc': {'slot': 8, 'casttime': 4.0, 'recasttime': 8.0},
    'cos': {'slot': 8, 'casttime': 5.0, 'recasttime': 1.5},
    'gic': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'ggd': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gwl': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gcs': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gkarana': {'slot': 8, 'casttime': 16.0, 'recasttime': 12.0},
    'gtoxx': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gbb': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gsfg': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gcl': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'glava': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gsteamfont': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gro': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gfear': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gmisty': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'gdawn': {'slot': 8, 'casttime': 24.0, 'recasttime': 10.0},
    'ggrim': {'slot': 8, 'casttime': 24.0, 'recasttime': 10.0},
    'gtwi': {'slot': 8, 'casttime': 24.0, 'recasttime': 10.0},
    'gdl': {'slot': 8, 'casttime': 16.0, 'recasttime': 10.0},
    'pot': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'pok': {'slot': 8, 'casttime': 10.0, 'recasttime': 6.0},
    'dena': {'slot': 8, 'casttime': 6.0, 'recasttime': 12.0},
}

spell_ids = {
    'heal': '1291', 'sow': '278', 'potg': '1442', 'cl': '25690', 'lev': '2894',
    'chloro': '145', 'thorns': '356', 'blades': '2125', 'regrowth': '1568', 'sln': '423',
    'natureskin': '1559', 'stormstrength': '430', 'cs': '25693', 'gd': '25696',
    'ic': '25698', 'wl': '25906', 'dl': '25694', 'bb': '25689', 'feerrott': '25695',
    'nk': '25899', 'lava': '24771', 'misty': '25699', 'ro': '25901', 'steamfont': '25902',
    'sfg': '25900', 'toxx': '25904', 'sf': '1736', 'ej': '1737', 'ba': '35', 'invis': '34',
    'counteractdisease': '96', 'resistdisease': '63', 'dawn': '24772', 'grim': '25697',
    'nexus': '25898', 'twi': '25905', 'soe': '2517', 'potc': '2188', 'cos': '2519',
    'gchloro': '138', 'gregrowth': '1569', 'gsow': '169', 'gthorns': '1727', 'gic': '1434',
    'ggd': '1438', 'gwl': '1398', 'gcs': '1440', 'gkarana': '550', 'gtoxx': '552', 'gbb': '553',
    'gsfg': '2020', 'gcl': '551', 'glava': '554', 'gsteamfont': '557', 'gro': '555', 'gfear': '556',
    'gmisty': '558', 'gdawn': '2429', 'ggrim': '2419', 'gtwi': '2424', 'gdl': '1517',
    'girdleofkarana': '1557', 'pot': '53155', 'pok': '24773', 'replenishment': '3433',
    'pot9': '3234', "bracken": "3448", "nmight": "3439", 'dena': '3579',
}

master_phrase_map = {
    'ds': 'blades',
    'dspl': 'thorns',
    'regen': 'regrowth',
    'regenpl': 'chloro',
    'heal': 'heal', 'sow': 'soe', 'potg': 'potg', 'cl': 'cl', 'levi': 'lev', 'lev': 'lev',
    'chloro': 'chloro', 'thorns': 'thorns', 'blades': 'blades', 'regrowth': 'regrowth',
    'sln': 'sln', 'natureskin': 'natureskin', 'stormstrength': 'stormstrength', 'cs': 'cs',
    'gd': 'gd', 'ic': 'ic', 'wl': 'wl', 'dl': 'dl', 'bb': 'bb', 'feerrott': 'feerrott',
    'nk': 'nk', 'lava': 'lava', 'misty': 'misty', 'ro': 'ro', 'steamfont': 'steamfont',
    'sfg': 'sfg', 'toxx': 'toxx', 'spirit of wolf': 'sow', 'glades': 'potg',
    'protection of the glades': 'potg', 'ec': 'cl', 'commons': 'cl', 'commonlands': 'cl',
    'common lands': 'cl', 'east commons': 'cl', 'levitate': 'lev', 'chloroplast': 'chloro',
    'skin like nature': 'sln', 'cobalt scar': 'cs', 'northk': 'nk', 'north karana': 'nk',
    'karana': 'nk', 'lavastorm': 'lava', 'lava storm': 'lava', 'misty thicket': 'misty',
    'nro': 'ro', 'sro': 'ro', 'northro': 'ro', 'north ro': 'ro', 'northern desert of ro': 'ro',
    'south ro': 'ro', 'sf': 'sf', 'steam font': 'steamfont', 'surefall': 'sfg',
    'sure fall': 'sfg', 'surefall glade': 'sfg', 'surefallglade': 'sfg', 'toxxulia': 'toxx',
    'toxxulia forest': 'toxx', 'great divide': 'gd', 'iceclad': 'ic', 'iceclad ocean': 'ic',
    'icecladocean': 'ic', 'wakening lands': 'wl', 'wakeninglands': 'wl', 'dreadlands': 'dl',
    'dread lands': 'dl', 'butcher': 'bb', 'butcherblock': 'bb', 'bbm': 'bb',
    'butcherblock mountains': 'bb', 'butcher block': 'bb', 'ferrott': 'feerrott',
    'feerott': 'feerrott', 'feerrot': 'feerrott', 'feerroot': 'feerrott', 'ferot': 'feerrott',
    'tox': 'toxx', 'ferroot': 'feerrott', 'ej': 'ej', 'emerald jungle': 'ej', 'emerald': 'ej',
    'skyfire': 'sf', 'sky fire': 'sf', 'skyfire mountains': 'sf', 'ba': 'ba', 'bind': 'ba',
    'bind affinity': 'ba', 'fear': 'feerrott', 'invis': 'invis', 'camo': 'invis',
    'camouflage': 'invis', 'superior camouflage': 'invis',
    'counteractdisease': 'counteractdisease',
    'cure disease': 'counteractdisease', 'resistdisease': 'resistdisease',
    'resist disease': 'resistdisease', 'disease resist': 'resistdisease', 'fearrott': 'feerrott',
    'ct': 'feerrott', 'mistythicket': 'misty', 'dawn': 'dawn', 'dawnshroud': 'dawn',
    'grimling': 'grim', 'grim': 'grim', 'nexus': 'nexus', 'nex': 'nexus',
    'twilight': 'twi', 'twi': 'twi', 'moon': 'nexus', 'ts': 'twi', 'dsp': 'dawn',
    'soe': 'soe', 'spirit of eagle': 'soe', 'eagle': 'soe', 'eagles': 'soe', 'potc': 'potc',
    'cabbage': 'potc', 'protection of the cabbage': 'potc', 'cos': 'cos', 'season': 'cos',
    'seasons': 'cos', 'gregenpl': 'gchloro', 'gregrowth': 'gregrowth', 'gsow': 'gsow',
    'gthorns': 'gthorns', 'gic': 'gic', 'ggd': 'ggd', 'gwl': 'gwl', 'gcs': 'gcs',
    'gkarana': 'gkarana', 'gtoxx': 'gtoxx', 'gbb': 'gbb', 'gsfg': 'gsfg', 'gcl': 'gcl',
    'glava': 'glava', 'gsteamfont': 'gsteamfont', 'gro': 'gro', 'gfear': 'gfear',
    'gmisty': 'gmisty', 'strength': 'stormstrength', 'gdawn': 'gdawn', 'ggrim': 'ggrim',
    'gtwi': 'gtwi', 'gdl': 'gdl', 'gchloro': 'gchloro', 'pot': 'pot', 'pok': 'pok',
    'tranq': 'pot', 'tranquility': 'pot', 'knowledge': 'pok', 'replenishment': 'replenishment',
    'pot9': 'pot9', '9': 'pot9', 'nine': 'pot9', 'potn': 'pot9', "bracken": "bracken",
    "sob": "bracken", "nmight": "nmight", "might": "nmight", 'dena': 'dena',
}

# must be grouped to cast these spells
group_spells = [
    'ej', 'sf', 'ba', 'invis', 'gic', 'ggd', 'gwl', 'gcs', 'gkarana', 'gtoxx', 'gbb', 'gsfg', 'gcl',
    'glava', 'gsteamfont', 'gro', 'gfear', 'gmisty', 'gdawn', 'ggrim', 'gtwi', 'gdl', 'dena',
]

failure_strings = [
    'spell fizzles',
    'You must first select a target for this spell!',
    "I don't see anyone by that name around here...",
    'Your spell is too powerful for your intended target.',
    'You have joined the group.',
    'You cannot memorize this spell.',
    'Insufficient Mana to cast this spell!',
    'To invite another group into yours, please invite the leader of the other group.',
    'Your target is out of range, get closer!'
]
